# Generated by Django 5.2.6 on 2025-09-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('links', models.JSONField(default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profile_app.project'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma separated skills'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, help_text='Comma separated skills', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='work',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='profile_app.work'),
        ),
    ]
